package com.ti.crowd_manager.domain;

import java.io.Serializable;
import java.util.Date;

public class Advertisement implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.id
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.item_id
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.item_name
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.image
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.status
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.create_time
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.id
     *
     * @return the value of advertisement.id
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.id
     *
     * @param id the value for advertisement.id
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.item_id
     *
     * @return the value of advertisement.item_id
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.item_id
     *
     * @param itemId the value for advertisement.item_id
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.item_name
     *
     * @return the value of advertisement.item_name
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.item_name
     *
     * @param itemName the value for advertisement.item_name
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.image
     *
     * @return the value of advertisement.image
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.image
     *
     * @param image the value for advertisement.image
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.status
     *
     * @return the value of advertisement.status
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.status
     *
     * @param status the value for advertisement.status
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.create_time
     *
     * @return the value of advertisement.create_time
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.create_time
     *
     * @param createTime the value for advertisement.create_time
     *
     * @mbg.generated Wed Jan 30 16:53:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}