package com.ti.crowd_manager.domain;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Item implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.uid
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.cid
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.intro
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.short_title
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String shortTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.current_money
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Double currentMoney=0d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.raise_money
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Double raiseMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.financing_days
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Integer financingDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.image
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.contribute_num
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Integer contributeNum=0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.linkman_name
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String linkmanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.linkman_introduction
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String linkmanIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.linkman_email
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String linkmanEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.linkman_phone
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String linkmanPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.linkman_qr_code
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private String linkmanQrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.create_time
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Date createTime;

    public String getCreateTimeStr(){
        return new SimpleDateFormat("yyyy-MM-dd hh:mm:ss").format(createTime);
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.update_time
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.status
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    private Integer status=0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.uid
     *
     * @return the value of item.uid
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.uid
     *
     * @param uid the value for item.uid
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.cid
     *
     * @return the value of item.cid
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.cid
     *
     * @param cid the value for item.cid
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.intro
     *
     * @return the value of item.intro
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.intro
     *
     * @param intro the value for item.intro
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.short_title
     *
     * @return the value of item.short_title
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.short_title
     *
     * @param shortTitle the value for item.short_title
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle == null ? null : shortTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.current_money
     *
     * @return the value of item.current_money
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Double getCurrentMoney() {
        return currentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.current_money
     *
     * @param currentMoney the value for item.current_money
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setCurrentMoney(Double currentMoney) {
        this.currentMoney = currentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.raise_money
     *
     * @return the value of item.raise_money
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Double getRaiseMoney() {
        return raiseMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.raise_money
     *
     * @param raiseMoney the value for item.raise_money
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setRaiseMoney(Double raiseMoney) {
        this.raiseMoney = raiseMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.financing_days
     *
     * @return the value of item.financing_days
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Integer getFinancingDays() {
        return financingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.financing_days
     *
     * @param financingDays the value for item.financing_days
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setFinancingDays(Integer financingDays) {
        this.financingDays = financingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.image
     *
     * @return the value of item.image
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.image
     *
     * @param image the value for item.image
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.contribute_num
     *
     * @return the value of item.contribute_num
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Integer getContributeNum() {
        return contributeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.contribute_num
     *
     * @param contributeNum the value for item.contribute_num
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setContributeNum(Integer contributeNum) {
        this.contributeNum = contributeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.linkman_name
     *
     * @return the value of item.linkman_name
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getLinkmanName() {
        return linkmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.linkman_name
     *
     * @param linkmanName the value for item.linkman_name
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setLinkmanName(String linkmanName) {
        this.linkmanName = linkmanName == null ? null : linkmanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.linkman_introduction
     *
     * @return the value of item.linkman_introduction
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getLinkmanIntroduction() {
        return linkmanIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.linkman_introduction
     *
     * @param linkmanIntroduction the value for item.linkman_introduction
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setLinkmanIntroduction(String linkmanIntroduction) {
        this.linkmanIntroduction = linkmanIntroduction == null ? null : linkmanIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.linkman_email
     *
     * @return the value of item.linkman_email
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getLinkmanEmail() {
        return linkmanEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.linkman_email
     *
     * @param linkmanEmail the value for item.linkman_email
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setLinkmanEmail(String linkmanEmail) {
        this.linkmanEmail = linkmanEmail == null ? null : linkmanEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.linkman_phone
     *
     * @return the value of item.linkman_phone
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getLinkmanPhone() {
        return linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.linkman_phone
     *
     * @param linkmanPhone the value for item.linkman_phone
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setLinkmanPhone(String linkmanPhone) {
        this.linkmanPhone = linkmanPhone == null ? null : linkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.linkman_qr_code
     *
     * @return the value of item.linkman_qr_code
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getLinkmanQrCode() {
        return linkmanQrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.linkman_qr_code
     *
     * @param linkmanQrCode the value for item.linkman_qr_code
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setLinkmanQrCode(String linkmanQrCode) {
        this.linkmanQrCode = linkmanQrCode == null ? null : linkmanQrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_time
     *
     * @return the value of item.create_time
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_time
     *
     * @param createTime the value for item.create_time
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_time
     *
     * @return the value of item.update_time
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_time
     *
     * @param updateTime the value for item.update_time
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.status
     *
     * @return the value of item.status
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.status
     *
     * @param status the value for item.status
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    //create by ti
    private String  itemDetail;

    public String getItemDetail() {
        return itemDetail;
    }

    public void setItemDetail(String itemDetail) {
        this.itemDetail = itemDetail;
    }

    private String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}