package com.ti.crowd_manager.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public ItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIntroIsNull() {
            addCriterion("intro is null");
            return (Criteria) this;
        }

        public Criteria andIntroIsNotNull() {
            addCriterion("intro is not null");
            return (Criteria) this;
        }

        public Criteria andIntroEqualTo(String value) {
            addCriterion("intro =", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotEqualTo(String value) {
            addCriterion("intro <>", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThan(String value) {
            addCriterion("intro >", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThanOrEqualTo(String value) {
            addCriterion("intro >=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThan(String value) {
            addCriterion("intro <", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThanOrEqualTo(String value) {
            addCriterion("intro <=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLike(String value) {
            addCriterion("intro like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotLike(String value) {
            addCriterion("intro not like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroIn(List<String> values) {
            addCriterion("intro in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotIn(List<String> values) {
            addCriterion("intro not in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroBetween(String value1, String value2) {
            addCriterion("intro between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotBetween(String value1, String value2) {
            addCriterion("intro not between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andShortTitleIsNull() {
            addCriterion("short_title is null");
            return (Criteria) this;
        }

        public Criteria andShortTitleIsNotNull() {
            addCriterion("short_title is not null");
            return (Criteria) this;
        }

        public Criteria andShortTitleEqualTo(String value) {
            addCriterion("short_title =", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleNotEqualTo(String value) {
            addCriterion("short_title <>", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleGreaterThan(String value) {
            addCriterion("short_title >", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleGreaterThanOrEqualTo(String value) {
            addCriterion("short_title >=", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleLessThan(String value) {
            addCriterion("short_title <", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleLessThanOrEqualTo(String value) {
            addCriterion("short_title <=", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleLike(String value) {
            addCriterion("short_title like", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleNotLike(String value) {
            addCriterion("short_title not like", value, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleIn(List<String> values) {
            addCriterion("short_title in", values, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleNotIn(List<String> values) {
            addCriterion("short_title not in", values, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleBetween(String value1, String value2) {
            addCriterion("short_title between", value1, value2, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andShortTitleNotBetween(String value1, String value2) {
            addCriterion("short_title not between", value1, value2, "shortTitle");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyIsNull() {
            addCriterion("current_money is null");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyIsNotNull() {
            addCriterion("current_money is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyEqualTo(Double value) {
            addCriterion("current_money =", value, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyNotEqualTo(Double value) {
            addCriterion("current_money <>", value, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyGreaterThan(Double value) {
            addCriterion("current_money >", value, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("current_money >=", value, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyLessThan(Double value) {
            addCriterion("current_money <", value, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyLessThanOrEqualTo(Double value) {
            addCriterion("current_money <=", value, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyIn(List<Double> values) {
            addCriterion("current_money in", values, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyNotIn(List<Double> values) {
            addCriterion("current_money not in", values, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyBetween(Double value1, Double value2) {
            addCriterion("current_money between", value1, value2, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andCurrentMoneyNotBetween(Double value1, Double value2) {
            addCriterion("current_money not between", value1, value2, "currentMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyIsNull() {
            addCriterion("raise_money is null");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyIsNotNull() {
            addCriterion("raise_money is not null");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyEqualTo(Double value) {
            addCriterion("raise_money =", value, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyNotEqualTo(Double value) {
            addCriterion("raise_money <>", value, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyGreaterThan(Double value) {
            addCriterion("raise_money >", value, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("raise_money >=", value, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyLessThan(Double value) {
            addCriterion("raise_money <", value, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyLessThanOrEqualTo(Double value) {
            addCriterion("raise_money <=", value, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyIn(List<Double> values) {
            addCriterion("raise_money in", values, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyNotIn(List<Double> values) {
            addCriterion("raise_money not in", values, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyBetween(Double value1, Double value2) {
            addCriterion("raise_money between", value1, value2, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andRaiseMoneyNotBetween(Double value1, Double value2) {
            addCriterion("raise_money not between", value1, value2, "raiseMoney");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysIsNull() {
            addCriterion("financing_days is null");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysIsNotNull() {
            addCriterion("financing_days is not null");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysEqualTo(Integer value) {
            addCriterion("financing_days =", value, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysNotEqualTo(Integer value) {
            addCriterion("financing_days <>", value, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysGreaterThan(Integer value) {
            addCriterion("financing_days >", value, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("financing_days >=", value, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysLessThan(Integer value) {
            addCriterion("financing_days <", value, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("financing_days <=", value, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysIn(List<Integer> values) {
            addCriterion("financing_days in", values, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysNotIn(List<Integer> values) {
            addCriterion("financing_days not in", values, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysBetween(Integer value1, Integer value2) {
            addCriterion("financing_days between", value1, value2, "financingDays");
            return (Criteria) this;
        }

        public Criteria andFinancingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("financing_days not between", value1, value2, "financingDays");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andContributeNumIsNull() {
            addCriterion("contribute_num is null");
            return (Criteria) this;
        }

        public Criteria andContributeNumIsNotNull() {
            addCriterion("contribute_num is not null");
            return (Criteria) this;
        }

        public Criteria andContributeNumEqualTo(Integer value) {
            addCriterion("contribute_num =", value, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumNotEqualTo(Integer value) {
            addCriterion("contribute_num <>", value, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumGreaterThan(Integer value) {
            addCriterion("contribute_num >", value, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("contribute_num >=", value, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumLessThan(Integer value) {
            addCriterion("contribute_num <", value, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumLessThanOrEqualTo(Integer value) {
            addCriterion("contribute_num <=", value, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumIn(List<Integer> values) {
            addCriterion("contribute_num in", values, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumNotIn(List<Integer> values) {
            addCriterion("contribute_num not in", values, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumBetween(Integer value1, Integer value2) {
            addCriterion("contribute_num between", value1, value2, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andContributeNumNotBetween(Integer value1, Integer value2) {
            addCriterion("contribute_num not between", value1, value2, "contributeNum");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameIsNull() {
            addCriterion("linkman_name is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameIsNotNull() {
            addCriterion("linkman_name is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameEqualTo(String value) {
            addCriterion("linkman_name =", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameNotEqualTo(String value) {
            addCriterion("linkman_name <>", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameGreaterThan(String value) {
            addCriterion("linkman_name >", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameGreaterThanOrEqualTo(String value) {
            addCriterion("linkman_name >=", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameLessThan(String value) {
            addCriterion("linkman_name <", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameLessThanOrEqualTo(String value) {
            addCriterion("linkman_name <=", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameLike(String value) {
            addCriterion("linkman_name like", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameNotLike(String value) {
            addCriterion("linkman_name not like", value, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameIn(List<String> values) {
            addCriterion("linkman_name in", values, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameNotIn(List<String> values) {
            addCriterion("linkman_name not in", values, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameBetween(String value1, String value2) {
            addCriterion("linkman_name between", value1, value2, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanNameNotBetween(String value1, String value2) {
            addCriterion("linkman_name not between", value1, value2, "linkmanName");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionIsNull() {
            addCriterion("linkman_introduction is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionIsNotNull() {
            addCriterion("linkman_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionEqualTo(String value) {
            addCriterion("linkman_introduction =", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionNotEqualTo(String value) {
            addCriterion("linkman_introduction <>", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionGreaterThan(String value) {
            addCriterion("linkman_introduction >", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("linkman_introduction >=", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionLessThan(String value) {
            addCriterion("linkman_introduction <", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionLessThanOrEqualTo(String value) {
            addCriterion("linkman_introduction <=", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionLike(String value) {
            addCriterion("linkman_introduction like", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionNotLike(String value) {
            addCriterion("linkman_introduction not like", value, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionIn(List<String> values) {
            addCriterion("linkman_introduction in", values, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionNotIn(List<String> values) {
            addCriterion("linkman_introduction not in", values, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionBetween(String value1, String value2) {
            addCriterion("linkman_introduction between", value1, value2, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanIntroductionNotBetween(String value1, String value2) {
            addCriterion("linkman_introduction not between", value1, value2, "linkmanIntroduction");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailIsNull() {
            addCriterion("linkman_email is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailIsNotNull() {
            addCriterion("linkman_email is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailEqualTo(String value) {
            addCriterion("linkman_email =", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailNotEqualTo(String value) {
            addCriterion("linkman_email <>", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailGreaterThan(String value) {
            addCriterion("linkman_email >", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailGreaterThanOrEqualTo(String value) {
            addCriterion("linkman_email >=", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailLessThan(String value) {
            addCriterion("linkman_email <", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailLessThanOrEqualTo(String value) {
            addCriterion("linkman_email <=", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailLike(String value) {
            addCriterion("linkman_email like", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailNotLike(String value) {
            addCriterion("linkman_email not like", value, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailIn(List<String> values) {
            addCriterion("linkman_email in", values, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailNotIn(List<String> values) {
            addCriterion("linkman_email not in", values, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailBetween(String value1, String value2) {
            addCriterion("linkman_email between", value1, value2, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanEmailNotBetween(String value1, String value2) {
            addCriterion("linkman_email not between", value1, value2, "linkmanEmail");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneIsNull() {
            addCriterion("linkman_phone is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneIsNotNull() {
            addCriterion("linkman_phone is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneEqualTo(String value) {
            addCriterion("linkman_phone =", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneNotEqualTo(String value) {
            addCriterion("linkman_phone <>", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneGreaterThan(String value) {
            addCriterion("linkman_phone >", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("linkman_phone >=", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneLessThan(String value) {
            addCriterion("linkman_phone <", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneLessThanOrEqualTo(String value) {
            addCriterion("linkman_phone <=", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneLike(String value) {
            addCriterion("linkman_phone like", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneNotLike(String value) {
            addCriterion("linkman_phone not like", value, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneIn(List<String> values) {
            addCriterion("linkman_phone in", values, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneNotIn(List<String> values) {
            addCriterion("linkman_phone not in", values, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneBetween(String value1, String value2) {
            addCriterion("linkman_phone between", value1, value2, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanPhoneNotBetween(String value1, String value2) {
            addCriterion("linkman_phone not between", value1, value2, "linkmanPhone");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeIsNull() {
            addCriterion("linkman_qr_code is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeIsNotNull() {
            addCriterion("linkman_qr_code is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeEqualTo(String value) {
            addCriterion("linkman_qr_code =", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeNotEqualTo(String value) {
            addCriterion("linkman_qr_code <>", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeGreaterThan(String value) {
            addCriterion("linkman_qr_code >", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("linkman_qr_code >=", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeLessThan(String value) {
            addCriterion("linkman_qr_code <", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeLessThanOrEqualTo(String value) {
            addCriterion("linkman_qr_code <=", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeLike(String value) {
            addCriterion("linkman_qr_code like", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeNotLike(String value) {
            addCriterion("linkman_qr_code not like", value, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeIn(List<String> values) {
            addCriterion("linkman_qr_code in", values, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeNotIn(List<String> values) {
            addCriterion("linkman_qr_code not in", values, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeBetween(String value1, String value2) {
            addCriterion("linkman_qr_code between", value1, value2, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andLinkmanQrCodeNotBetween(String value1, String value2) {
            addCriterion("linkman_qr_code not between", value1, value2, "linkmanQrCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 27 13:43:57 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}