package com.ti.crowd_manager.mapper;

import com.ti.crowd_manager.domain.ItemCat;
import com.ti.crowd_manager.domain.ItemCatExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    long countByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int deleteByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int insert(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int insertSelective(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    List<ItemCat> selectByExample(ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    ItemCat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemCat record, @Param("example") ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByExample(@Param("record") ItemCat record, @Param("example") ItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByPrimaryKeySelective(ItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_cat
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByPrimaryKey(ItemCat record);

    //create by ti
    void updateById(ItemCat itemCat);
}