package com.ti.crowd_manager.mapper;

import com.ti.crowd_manager.domain.ItemDetail;
import com.ti.crowd_manager.domain.ItemDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    long countByExample(ItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int deleteByExample(ItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int insert(ItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int insertSelective(ItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    List<ItemDetail> selectByExampleWithBLOBs(ItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    List<ItemDetail> selectByExample(ItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    ItemDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemDetail record, @Param("example") ItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ItemDetail record, @Param("example") ItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByExample(@Param("record") ItemDetail record, @Param("example") ItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail
     *
     * @mbg.generated Sun Jan 27 13:43:57 CST 2019
     */
    int updateByPrimaryKey(ItemDetail record);
}